#ifndef _CONF_H_
#define _CONF_H_

#define AJJ_SYMBOL_NAME_MAX_SIZE 32
#define AJJ_GLOBAL_SYMBOL_MAX_SIZE 256
#define AJJ_LOCAL_CONSTANT_SIZE 128
#define AJJ_EXTENDS_MAX_SIZE 8
#define AJJ_FUNC_LOCAL_BUF_SIZE 16
#define AJJ_FUNC_ARG_MAX_SIZE 24
#define AJJ_MAX_CALL_STACK 128
#define AJJ_MAX_VALUE_STACK_SIZE 1024
#define AJJ_MAX_NESTED_INCLUDE_SIZE 128

#endif /* _CONF_H_ */
